version: '3.4'

services:
  tpp.api:
    container_name: tpp.api
    image: ${DOCKER_REGISTRY-}tppapi
    build:
      context: .
      dockerfile: TPP.Api/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
    ports:
      - "51830:80"
      - "51836:443"

  tpp.bot.host:
    container_name: tpp.bot.host
    image: ${DOCKER_REGISTRY-}tppbothost
    build:
      context: .
      dockerfile: TPP.Bot.Host/Dockerfile
 
  postgres:
    container_name: postgres
    image: postgres
    environment:
        POSTGRES_DB: TPP.db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: thebestpassword123
    ports:
        - "5450:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  postgres-data: